package domain

import "time"

// StepStatus represents the lifecycle state of an individual plan step.
type StepStatus string

const (
	StepStatusPending   StepStatus = "pending"
	StepStatusRunning   StepStatus = "running"
	StepStatusCompleted StepStatus = "completed"
	StepStatusFailed    StepStatus = "failed"
	StepStatusSkipped   StepStatus = "skipped"
)

// Plan is an ordered list of steps generated by the agent planner for a task.
type Plan struct {
	ID        string
	TaskID    string
	Steps     []*PlanStep
	CreatedAt time.Time
}

// PlanStep is a single actionable step within a plan.
type PlanStep struct {
	ID          string
	PlanID      string
	Order       int
	Title       string
	Description string
	Status      StepStatus
	ToolName    string // empty if this is a reasoning/thinking step
	ToolInput   string // JSON-encoded tool arguments
	ToolOutput  string // JSON-encoded tool result
	StartedAt   *time.Time
	CompletedAt *time.Time
}
